name: Javadoc

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Create Javadoc
        run: ./gradlew javadoc